version: 1.0.0.{build}

platform: Any CPU

before_build:
  - nuget restore KerSSH.sln

build:
  project: KerSSH.sln

#---------------------------------#
#         Deploy to GH            #
#---------------------------------#

deploy:
  release: KerSSH_v$(appveyor_build_version)
  description: 'Automatic release from AppVeyor'
  provider: GitHub
  auth_token:
    secure: 7ZwM4M+GML/Gcdi8xiAIevqGDL+EF5yUM00KEh0JN7lRFP5YwU3/D/KIivo4pWId
  artifact: bin\$(configuration)\            # upload all NuGet packages to release assets
  draft: true
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Slack
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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